In [13]:
cur_path = '/Users/Joey/Projects/NBA_player_tracking/data/'

In [14]:
import pandas as pd
import numpy as np

In [15]:
shot_attempts_all = pd.read_csv(cur_path+'shot_attempts_all_dist.csv')
shot_attempts_all.head()

,game_id,quarter,game_clock,q_game_clock,join_clock,ball_id,ball_team_id,ball_x_loc,ball_y_loc,p1_id,...,p1_dist_from_ball,p2_dist_from_ball,p3_dist_from_ball,p4_dist_from_ball,p5_dist_from_ball,p6_dist_from_ball,p7_dist_from_ball,p8_dist_from_ball,p9_dist_from_ball,p10_dist_from_ball
0,21500118,1,10.81,1010.81,215001181010,-1,-1,88.58073,47.23678,1717,...,25.251916,16.981250,22.637161,20.304444,6.750220,21.553423,40.943990,26.906010,0.060198,34.652225
1,21500118,1,34.82,1034.82,215001181034,-1,-1,19.72510,38.33816,1717,...,18.720376,5.516566,12.141578,0.823278,7.722781,5.329583,7.280693,19.003480,18.202907,10.806135
2,21500118,1,75.11,1075.11,215001181075,-1,-1,5.07477,27.30752,1717,...,25.041458,24.732430,27.791431,4.689703,1.816031,4.939779,9.428115,3.260305,7.047434,5.547414
3,21500118,1,96.34,1096.34,215001181096,-1,-1,63.16144,20.32074,1717,...,26.373570,23.195343,6.204567,7.622843,21.034415,0.940962,25.207678,29.016448,30.794489,17.524849
4,21500118,1,112.74,1112.74,215001181112,-1,-1,8.62189,35.09709,1717,...,0.593693,32.487279,21.978892,24.644689,24.167873,8.811112,21.294261,3.879000,17.827434,12.340423

In [16]:
team_id_list = list(shot_attempts_all['shot_team_id'])
closest_player = []
closest_dist = []
closest_x = []
closest_y = []
for i in range(len(shot_attempts_all)):
  shooter_team = team_id_list[i]
  min_dist = 9999
  for j in range(-10,0,1):
    if j == -1:
      p_id = shot_attempts_all.columns[j][0:3]
    else:
      p_id = shot_attempts_all.columns[j][0:2]
    p_team = shot_attempts_all[p_id+'_team_id'].iloc[i]
    dist = shot_attempts_all.iloc[i,j]
    player = shot_attempts_all[p_id+'_id'].iloc[i]
    x_loc = shot_attempts_all[p_id+'_x_loc'].iloc[i]
    y_loc = shot_attempts_all[p_id+'_y_loc'].iloc[i]
    if (p_team != shooter_team) and (dist < min_dist):
      min_dist = dist
      p_id_closest = player
      x_loc_closest = x_loc
      y_loc_closest = y_loc
  closest_dist.append(min_dist)
  closest_player.append(p_id_closest)
  closest_x.append(x_loc_closest)
  closest_y.append(y_loc_closest)

In [17]:
shooter_x = []
shooter_y = []
for i in range(len(shot_attempts_all)):
  shooter = shot_attempts_all['shooter_id'].iloc[i]
  for j in range(1,11,1):
    p_id = shot_attempts_all['p'+str(j)+'_id'].iloc[i]
    if (shooter == p_id):
      x_loc = shot_attempts_all['p'+str(j)+'_x_loc'].iloc[i]
      y_loc = shot_attempts_all['p'+str(j)+'_y_loc'].iloc[i]
      break
  shooter_x.append(x_loc)
  shooter_y.append(y_loc)

In [18]:
shot_attempts_all['p_id_nearest_def'] = closest_player
shot_attempts_all['nearest_def_dist'] = closest_dist
shot_attempts_all['nearest_def_x_loc'] = closest_x
shot_attempts_all['nearest_def_y_loc'] = closest_y
shot_attempts_all['shooter_x_loc'] = shooter_x
shot_attempts_all['shooter_y_loc'] = shooter_y
shot_attempts_all.head()

,game_id,quarter,game_clock,q_game_clock,join_clock,ball_id,ball_team_id,ball_x_loc,ball_y_loc,p1_id,...,p7_dist_from_ball,p8_dist_from_ball,p9_dist_from_ball,p10_dist_from_ball,p_id_nearest_def,nearest_def_dist,nearest_def_x_loc,nearest_def_y_loc,shooter_x_loc,shooter_y_loc
0,21500118,1,10.81,1010.81,215001181010,-1,-1,88.58073,47.23678,1717,...,40.943990,26.906010,0.060198,34.652225,1626147,6.750220,88.64105,40.48683,88.53623,47.27732
1,21500118,1,34.82,1034.82,215001181034,-1,-1,19.72510,38.33816,1717,...,7.280693,19.003480,18.202907,10.806135,1718,5.329583,22.89819,34.05611,20.54730,38.29605
2,21500118,1,75.11,1075.11,215001181075,-1,-1,5.07477,27.30752,1717,...,9.428115,3.260305,7.047434,5.547414,2746,3.260305,7.14406,24.78807,6.11990,25.82237
3,21500118,1,96.34,1096.34,215001181096,-1,-1,63.16144,20.32074,1717,...,25.207678,29.016448,30.794489,17.524849,200826,6.204567,68.40022,16.99631,62.22048,20.31882
4,21500118,1,112.74,1112.74,215001181112,-1,-1,8.62189,35.09709,1717,...,21.294261,3.879000,17.827434,12.340423,2746,3.879000,6.81804,31.66303,8.27183,35.57660

In [19]:
shot_attempts_all.to_csv(cur_path+'shot_attempts_all_nearest_def.csv', index=False)